// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hgyghtaraqljqpugorze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhneWdodGFyYXFsanFwdWdvcnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3MTc5ODMsImV4cCI6MjA5NDI5Mzk4M30.c7M_aSzHpnlV2J5nUAXp6kelV5eAJeEMxxTmhLhIOeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);